// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"example-wire/onion_architecture/controller"
	"example-wire/onion_architecture/repository"
	"example-wire/onion_architecture/service"
)

// Injectors from wire.go:

func InitControllers() controller.Controller {
	repositories := repository.NewRepositories()
	services := service.NewServices(repositories)
	controllerController := controller.NewControllers(services)
	return controllerController
}
